name: Deploy Jurassic Park Remote MCP server

run-name: Deploy Jurassic Park Remote MCP server

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  DeployApp:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: Dev
    timeout-minutes: 5

    steps:
      - name: Download Jurassic Park MCP artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          branch: main
          workflow_conclusion: success
          path: artifact
          name: jurassicpark-mcp-artifact

      - name: Azure login
        uses: Azure/login@v2.3.0
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Deploy remote MCP server
        uses: Azure/webapps-deploy@v3.0.6
        with:
          app-name: jurassicpark-mcp
          package: artifact/jurassicpark.mcp.zip
